name: Validation

on:
  pull_request:
  push:
    branches:
      - f/**
      - p/**
      - next
      - master
      - main

jobs:
  lint_build_test:
    name: Lint, Build & Test
    env:
      DBURL: mongodb://localhost:27017/mgdb-migrator-db
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x, lts/*, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
