name: Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint_build_test:
    name: Lint, Build & Test
    env:
      DBURL: mongodb://localhost:27017/mgdb-migrator-db
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18, 20, 22, lts/*, latest]
        mongodb-version: ['^4.17.2', '^5']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies, including the specified MongoDB driver
        run: npm install mongodb@"${{ matrix.mongodb-version }}"

      - name: List installed mongodb version
        run: npm list mongodb

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
